version: 2
jobs:
  shellcheck:
    docker: 
      - image: nlknguyen/alpine-shellcheck:v0.4.6
      - image: circleci/node:chakracore-8-browsers-legacy
      - image: docker:stable-git
    steps: 
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
            pwd
            ls -a
            git status
            node --version
  build:
    docker:
      - image: circleci/node@sha256:9ad2cc2e228dc5f00ac5dcaf3fd83dcedfee4b3a6f779515060070c46891fa10
    steps:
      - run: echo "A first hello"
workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build:
          requires:
            - shellcheck
          filters:
            branches: 
              only: master